<!文档类型 html>
<HTML lang=“en">

<头>
    <元字符集=“UTF-8">
    <meta http-equiv=“X-UA-Compatible” content=“IE=edge">
    <元名称=“视口” 内容=“宽度=设备宽度，初始比例=1.0">
    <链接 rel=“快捷方式图标” href=“../../图片/徽标.ico" />
    <脚本类型=“文本/JavaScript” src=“homework06.js”></script>
    <链接 rel=“样式表” href=“家庭作业06.css">
    <title>第六次作业</title>
</头>

<身体>
    <p>企业发放的奖金根据利润提成。<br/><br/> 1、利润低于或等于10万元时，奖金可提10%;
        <br/> 2、利润高于10万元，低于20万元时，低于10万元的部分按10%提成，高于10万元的部分，可提成7.5%;
        <br/> 3、20万到40万之间时，高于20万元的部分，可提成5%;
        <br/> 4、40万到60万之间时高于40万元的部分，可提成3%;
        <br/> 5、60万到100万之间时，高于60万元的部分，可提成1.5%;
        <br/> 6、高于100万元时，超过100万元的部分按1%提成。
        <br/><br/> 假设当月利润为 <input id=“data” type=“text” value=“374483”> 元，求应发放奖金总数？ （保留两位小数）

        <!-- <button id=“btn”>试试吧</按钮> -->
    </p>
应发奖金为：<span id=“result”></span>
</身体>

</.html>
